### ISSUE TITLE
/check mentions not working

### ISSUE THREAD

**Issue by CofJelly** [BurnsCommaLucas/ready-bot#38]
I get the following error message when using /check mentions: @CofJelly

You'll need to select some users to create a mentions check. Keep in mind I can't wait for bots or roles.
If you'd like to wait for a number of users rather than specific users, use /check count

This happens as well if I put other people, multiple people, roles, etc. Am I doing something wrong with the syntax?

**Comment by BurnsCommaLucas** [comment]
If you're pasting a pre-written check like that into the chat, I believe the mentions (like `@CofJelly` etc) aren't automatically parsed/picked up by Discord. The bot will still see the name, but unless Discord highlights the mention(s) they won't be possible for the bot to pick up on. Here's the difference:

Mention is not picked up by Discord, can't be picked up by the bot, looks like:
<img width="425" alt="Screen Shot 2023-02-18 at 3 23 26 PM" src="https://user-images.githubusercontent.com/9172192/219903846-93f5ddcf-38e2-4b63-9216-4bf54797d6dc.png">

Mention is picked up by Discord, can then be picked up by the bot, looks like:
<img width="432" alt="Screen Shot 2023-02-18 at 3 23 37 PM" src="https://user-images.githubusercontent.com/9172192/219903864-4d296aae-6224-4d28-b751-63af0c2aec74.png">

If the mentions you're putting in chat are in fact being highlighted like this but the bot is still not working for you, let me know and I'll look into things further.

**Comment by CofJelly** [comment]
![image](https://user-images.githubusercontent.com/53623597/219904388-5de0b821-96bb-49ba-b03c-3d9d9490bb77.png)

results in 

![image](https://user-images.githubusercontent.com/53623597/219904394-40f623bf-dbe0-4047-b7a6-02b45d0653fd.png)

**Comment by BurnsCommaLucas** [comment]
@CofJelly can you confirm whether this happens on any other servers with `ready-bot`? If you don't currently have any other servers that use `ready-bot` you can also join the support server to test it out: https://discord.com/invite/uwkF27Gt9M

**Comment by danfelix-dev** [comment]
Hello, I can tell that this is happening in our server, how can I help?

**Comment by BurnsCommaLucas** [comment]
In testing this with CofJelly I was unable to find what the issue is in the bot, and I haven't had time to look into a fix. I'll see about adding some logging to the system so that I can tell what's happening internally at the time the checks are failing. 

@danfelix-dev is this happening to all users on your server, or just certain users?

**Comment by BurnsCommaLucas** [comment]
Hey all, I'm making an effort to fix this issue by doing a ground up rewrite of the bot in another language that I'm more familiar with. The bot will operate in a near identical way, but my goal with this rewrite is to make it more reliable and debug-able. I'm not taking the bot down, and this repo will still exist, but I'm moving development over to [a new repo](https://github.com/BurnsCommaLucas/ready-botlin).

Once I spin up that new version in place of this one I'll re-create this ticket in that repo so we can see if the problem has been fixed.

**Comment by BurnsCommaLucas** [comment]
@CofJelly @danfelix-dev if you have a chance, please check out the bot again and see if this issue is still happening when you try to create checks. I created a new issue in the new repo to track this, so please put your feedback over there: https://github.com/BurnsCommaLucas/ready-botlin/issues/2
